language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c 'create database ireporter;' -U postgres

script:
  - py.test -v --cov-report term-missing --cov app 
  
after_success:
  - coveralls